In [94]:
import pandas as pd

In [95]:
df=pd.read_csv("C:/Users/Tufail/Desktop/Makshu/Jupyter/CsvFile/IMDB Dataset.csv")

In [96]:
df.shape

(50000, 2)

In [97]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [98]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [99]:
df.drop_duplicates(inplace=True)

In [100]:
df.shape

(49582, 2)

## PreProcessing

### 1.Converting to lowercase

In [101]:
df["review"]=df["review"].str.lower()

### 2.Removing the URLs

In [102]:
#we are repl http://www.xyz.com 
import re

def remove_url(text):
    text=re.sub(r"http\Se","",(text))  #(pattern,repl,string)
    return text

df["review"]=df["review"].apply(remove_url)

### 3. Removeing Punctuations

In [103]:
def remove_punctuations(text):
    text=re.sub(r"[^A-Za-z0-9\s]","",text)  #excluted A-Za-z-0-9
    return text

df["review"]=df["review"].apply(remove_punctuations)

### 4.Removing HTML

In [104]:
def remove_html(text):
    text=re.sub(r"<.*?>","",text)  # . --> any character  * --> 0 or more char
    return text                    # ? --> none greed manner(mean when first closing char get than stop)
    
df["review"]=df["review"].apply(remove_html)

### 5.Removing Stopword

In [105]:
import nltk    # help remove stop word

nltk.download("punkt")   #tokenisation --> help divid text into indivisival 
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Tufail\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Tufail\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Tufail\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [106]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [107]:
# Example
sample_text="I like coding in python"
tokens=word_tokenize(sample_text)

tokens

['I', 'like', 'coding', 'in', 'python']

In [108]:
def remove_stopwords(text):
    tokens=word_tokenize(text)  #tokenier
    stop_words=stopwords.words("english")  #getting stopword

    for word in tokens:     #help remove stopword
        if word in stop_words:
            text.replace(word,"")
    return text

df["review"]=df["review"].apply(remove_stopwords)

In [109]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

### 6.Stemming

In [110]:
#running -->run
#playing -->play

#PorterStemming    popular stemming

from nltk.stem import PorterStemmer

In [111]:
def stemming(text):
    ps=PorterStemmer()
    stemmed_word=[]

    tokens=word_tokenize(text)  # token help for stem
    for token in tokens:
        stemmed_token=ps.stem(token)
        stemmed_word.append(stemmed_token)

    return " ".join(stemmed_word)  # convert to string

df["review"]=df["review"].apply(stemming)

In [112]:
df.head()

                                              review sentiment
0  one of the other review ha mention that after ...  positive
1  a wonder littl product br br the film techniqu...  positive
2  i thought thi wa a wonder way to spend time on...  positive
3  basic there a famili where a littl boy jake th...  negative
4  petter mattei love in the time of money is a v...  positive

### 7.Encoding

In [113]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

df["sentiment"]=le.fit_transform(df["sentiment"])

In [114]:
y=df["sentiment"]
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

### 8.Vectorization

In [115]:
df.head()

                                              review  sentiment
0  one of the other review ha mention that after ...          1
1  a wonder littl product br br the film techniqu...          1
2  i thought thi wa a wonder way to spend time on...          1
3  basic there a famili where a littl boy jake th...          0
4  petter mattei love in the time of money is a v...          1

In [116]:
# TF-IDF 

from sklearn.feature_extraction.text import TfidfVectorizer

tf=TfidfVectorizer(max_features=5000)

X=tf.fit_transform(df["review"])

In [117]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5871158 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3124)	0.02032251735685024
  (0, 3099)	0.09542098470744526
  (0, 4441)	0.20903467205715237
  (0, 3153)	0.057164905655617715
  (0, 3689)	0.04795018941759714
  (0, 2026)	0.024837126680226217
  (0, 2811)	0.05093623457657249
  (0, 4439)	0.06274954229236089
  (0, 162)	0.032260181258981106
  (0, 4820)	0.07851591273828991
  (0, 2477)	0.04850405470299644
  (0, 3186)	0.43216782713328356
  (0, 1535)	0.10274122058172444
  (0, 4987)	0.05287089753313154
  (0, 443)	0.05711365014241208
  (0, 2180)	0.07161368973329611
  (0, 4456)	0.024446041394784856
  (0, 300)	0.041296577361905513
  (0, 3712)	0.08249984253761973
  (0, 324)	0.07507443472841555
  (0, 4461)	0.04274859304710011
  (0, 2388)	0.1295866356729789
  (0, 1583)	0.05594527309388424
  (0, 4864)	0.049933268194460693
  (0, 2054)	0.04118502050404425
  :	:
  (49581, 2287)	0.09370049477083149
  (49581, 1655)	0.16515065743591884
  (49581, 2208)	0.0807050171213464
  (49581, 4604)	0.09124520635183705
  (49581, 776)	0.10606814986101117
  (49581, 3828)	0.0969614002395767
  (49581, 2525)	0.10984319095358464
  (49581, 4659)	0.0994442296449171
  (49581, 2587)	0.09254382643575335
  (49581, 2355)	0.13974759078626203
  (49581, 379)	0.11062351220232874
  (49581, 2062)	0.12366306939993575
  (49581, 3640)	0.10501109054108233
  (49581, 2268)	0.1603929003910312
  (49581, 317)	0.10474191443679787
  (49581, 4585)	0.1548917714869443
  (49581, 2513)	0.17800008244249405
  (49581, 4161)	0.1951942180887046
  (49581, 1089)	0.15522934182669346
  (49581, 683)	0.1432055922664932
  (49581, 3026)	0.15987763334791602
  (49581, 2944)	0.16869126598604967
  (49581, 778)	0.12541386082039135
  (49581, 1958)	0.1531895792131522
  (49581, 3641)	0.14696302897312627

# Dataset & DataLoaders

In [118]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [119]:
X_train.shape

(39665, 5000)

In [120]:
import torch
from torch.utils.data import TensorDataset,DataLoader

In [121]:
X_train
#its is a sparse matrix we not directly

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4699376 stored elements and shape (39665, 5000)>

In [122]:
X_train=X_train.toarray()
X_test=X_test.toarray()

In [123]:
X_train

array([[0.21579409, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]], shape=(39665, 5000))

In [129]:
train_set=TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float()
)

test_set=TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float()
)

In [130]:
train_loader=DataLoader(train_set,shuffle=True,batch_size=64)
test_loader=DataLoader(test_set,shuffle=True,batch_size=64)

# Build RNN

In [131]:
import torch.nn as nn
import torch.optim as optim

In [142]:
class RNN(nn.Module):
    def __init__(self,input_size,hidden_size=128,num_layers=1):
        super().__init__()

        self.hidden_size=hidden_size
        self.num_layers=num_layers

        #RNN layer
        self.rnn=nn.RNN(input_size,hidden_size,num_layers,batch_first=True)

        #fully connected layer
        self.fc=nn.Linear(hidden_size,1)

    def forward(self,x):
        h0=torch.zeros(self.num_layers,x.size(0),self.hidden_size)

        out,_=self.rnn(x,h0)
        #1st value=hidden state of all the timesteps==>(batch ,seq,hidden size)
        #2nd value=final hidden state of ladt timestap

        out=self.fc(out[:,-1,:])
        return out

In [143]:
input_size=X_train.shape[1]

model=RNN(input_size)

criterion=nn.BCELoss()
optimizer=optim.Adam(model.parameters())

# Training the RNN

In [146]:
epochs=10

for epoch in range(epochs):
    model.train()

    for xb,yb in train_loader:
        optimizer.zero_grad()

        xb=xb.unsqueeze(1)  #2d to 3d model expect 3d

        outputs=model(xb)  #output is 2d

        outputs=torch.sigmoid(outputs.squeeze()) #covert to 1d

        loss=criterion(outputs,yb) #comput loss

        loss.backward()

        optimizer.step()  #weight update

    print(f"epoch={epoch}/{epochs} and loss ={loss.item()}")

epoch=0/10 and loss =0.3123336434364319
epoch=1/10 and loss =0.15917213261127472
epoch=2/10 and loss =0.2621256411075592
epoch=3/10 and loss =0.10963869094848633
epoch=4/10 and loss =0.11043860018253326
epoch=5/10 and loss =0.2145613133907318
epoch=6/10 and loss =0.2530892491340637
epoch=7/10 and loss =0.154904305934906
epoch=8/10 and loss =0.2901243269443512
epoch=9/10 and loss =0.323456346988678

In [149]:
#evalute

model.eval()

with torch.no_grad():
    correct_vals=0
    tot_vals=0

    for xb,yb in test_loader:
        xb=xb.unsqueeze(1)

        outputs=model(xb)

        predicted=(torch.sigmoid(outputs.squeeze(1))>0.5).float()

        tot_vals+=yb.size(0)
        correct_vals+=(predicted==yb).sum().item()

    print(f"accuracy={correct_vals/tot_vals} ")

accuracy=0.8706261974387416